version: '3'

tasks:
  dev:
    desc: Run Hugo server with draft mode enabled
    cmds:
      - hugo server -D

  commit:
    desc: Build site, commit and push changes to both repositories
    cmds:
      - echo "Building site with Hugo..."
      - hugo
      - cmd: |
          cd public
          echo "Committing public repository with message: {{.MSG}}"
          git add .
          git commit -m "{{.MSG}}"
          git push origin
      - cmd: |
          echo "Committing main repository with message: {{.MSG}}"
          git add .
          git commit -m "{{.MSG}}"
          git push origin
      - echo "All changes committed and pushed successfully."
    vars:
      MSG: '{{default "update content" .m}}'